server:
  port: 8006
  servlet:
    context-path: /rag
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: rag
  profiles:
    active: @profiles.active@
  ai:
    dashscope:
      api-key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx