server:
  port: 8002
  servlet:
    context-path: /mcp/server/stdio
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: mcp-server-stdio
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: mcp-server
        version: 1.0.0
        stdio: true # 开启 stdio
        enabled: true
        type: SYNC

logging:
  level:
    root: OFF