server:
  port: 8000
  servlet:
    context-path: /ai
spring:
  application:
    name: spring-ai
  profiles:
    active: @profiles.active@
  ai:
    dashscope:
      api-key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx